version: '3.7'
services:
  dequiz_mongo:
    container_name: dequiz_mongo
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    hostname: dequiz_mongo
    volumes:
      - dequiz_mongo:/data/db
    env_file:
      - mongo.env
    networks:
      backend:
        ipv4_address: 10.5.0.13

volumes:
  dequiz_mongo:

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
